name: imboy
description: A new Flutter project for IM.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  # getx 状态管理框架
  get: ^4.6.5
  #演示列表需要用到的库
  dio: ^4.0.6    #网络请求框架
  json_annotation: ^4.5.0 #json序列化和反序列化用的
  permission_handler: ^9.2.0
  camera: ^0.9.8+1
  wechat_camera_picker: ^3.4.0
  wechat_assets_picker: ^7.3.2
  # 一组基于 PointyCastle 的高级 API，用于双向加密。 RSA AES
  encrypt: ^5.0.1
  # 在纯 Dart 中实现的一组加密函数。  SHA-* MD5 HMAC
  # crypto: ^3.0.2
  # Flutter 开发者的密码学：加密、数字签名、密钥协议等。
  # AES, Chacha20, ED25519, X25519, and more. Web Crypto support.
  # https://github.com/dint-dev/cryptography
  # cryptography: ^2.0.5
  # cryptography_flutter: ^2.0.2
  # e2ee
  #webcrypto: ^0.5.2
  web_socket_channel: ^2.2.0
  # jwt 插件
  jose: ^0.3.2

  # 缓存
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_cache_manager: ^3.3.0

  logger: ^1.1.0
  # sentry_flutter: ^6.6.0
  photo_view: ^0.13.0
  extended_text: ^9.1.0
  extended_text_field: ^10.1.0
  lpinyin: ^2.0.3
  azlistview: ^2.0.0
  # 视频播放器
  video_player: ^2.4.5
  chewie: ^1.3.4
  webview_flutter: ^3.0.4
  image_picker: ^0.8.5+3
  #flutter_chat_ui: ^1.5.2
  mime: ^1.0.2
  file_picker: ^4.6.1
  open_file: ^3.2.1
  sqflite: ^2.0.2+1
  # 是否联网及网络类型
  connectivity_plus: ^2.3.5
  flutter_screenutil: ^5.5.3+2
  pull_to_refresh: ^2.0.0
  package_info_plus: ^1.4.2
  device_info_plus: ^3.2.4
  event_bus: ^2.0.0
  # https://github.com/letsar/flutter_slidable
  flutter_slidable: ^1.3.0
  # 消息提醒的红点效果
  badges: ^2.0.3
  # 聊天气泡
  bubble: ^1.2.1
  xid: ^1.0.7
  fps_monitor: ^2.0.0
  # @ 小部件
  flutter_mentions: ^2.0.1
  # 搜索页面
  search_page: ^2.0.0+1
  # 时间处理
  jiffy: ^5.0.0
  # 用于校正本地系统与时钟源服务器之前的时间
  ntp: ^2.0.0
  emoji_picker_flutter: ^1.3.0
  carousel_slider: ^4.1.1
  flutter_dotenv: ^5.0.2
  # popup_menu:
  #  path: plugin/popup_menu
  photo_manager: ^2.1.4
  video_compress: ^3.1.1
  path_provider: ^2.0.11
  flutter_login: ^4.0.0
  image_crop: ^0.4.0
  # 进度条
  percent_indicator: ^4.2.2
  json_serializable: ^6.2.0
  # 录音
  flutter_sound: ^9.2.13
  flutter_sound_platform_interface: ^9.2.13
  audio_session: ^0.1.8
  # 上传下载进度条显示
  flutter_easyloading: ^3.0.5
  # 生成闪屏页
  flutter_native_splash: ^2.2.3+1
  huawei_account: ^6.1.0+304
  #flutter_chat_ui: ^1.5.8
  flutter_chat_ui:
    path: plugin/flutter_chat_ui
  # popup_menu: ^1.0.5
  popup_menu:
    git:
      url: https://gitee.com/imboy-tripartite-deps/popup_menu.git
      ref: master
  niku: ^2.3.1
  mobile_scanner: ^2.0.0
  qr_flutter: ^4.0.0
  url_launcher: ^6.1.4
  image_gallery_saver: ^1.7.1
#  flutter_login:
#    path: plugin/flutter_login

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/.env
    - assets/data/region.json
    - assets/images/def_avatar.png
    - assets/images/splash_bg.png
    - assets/images/logo.png
    - assets/images/ic_index_bar_bubble_gray.png

    - assets/images/chat/voice_playing_1.png
    - assets/images/chat/voice_playing_2.png
    - assets/images/chat/voice_playing_3.png
    - assets/images/chat/voice_volume_1.png
    - assets/images/chat/voice_volume_2.png
    - assets/images/chat/voice_volume_3.png
    - assets/images/chat/voice_volume_4.png
    - assets/images/chat/voice_volume_5.png
    - assets/images/chat/voice_volume_6.png
    - assets/images/chat/voice_volume_7.png

    - assets/images/chat/input_voice.png
    - assets/images/chat/input_emoji.png
    - assets/images/chat/input_extra.png
    - assets/images/chat/input_keyboard.png
    - assets/images/conversation/sending.png

    - assets/images/chat/extra_photo.webp # 照片 extra_photo.webp
    - assets/images/chat/extra_camera.webp # 拍摄  extra_camera.webp
    - assets/images/chat/extra_videocall.webp # 视频通话  extra_camera.webp
    - assets/images/chat/extra_localtion.webp # 位置 extra_localtion.webp
    - assets/images/chat/extra_media.webp # 语音通话 extra_media.webp
    - assets/images/chat/extra_voice.webp # 语音输入  extra_voice.webp
    - assets/images/chat/extra_favorite.webp # 收藏  extra_favorite.webp
    - assets/images/chat/extra_card.webp # 个人名片 extra_card.webp
    - assets/images/chat/extra_file.webp # 文件  extra_file.webp
    - assets/images/chat/extra_wallet.png # 卡券 extra_wallet.png
    - assets/images/chat/extra_red.webp

    - assets/images/bar_close.png
    - assets/images/tabbar_contacts_c.webp
    - assets/images/tabbar_contacts_s.webp
    - assets/images/tabbar_discover_c.webp
    - assets/images/tabbar_discover_s.webp
    - assets/images/tabbar_chat_c.webp
    - assets/images/tabbar_chat_s.webp
    - assets/images/tabbar_me_c.webp
    - assets/images/tabbar_me_s.webp
    - assets/images/def_avatar.png
    - assets/images/search_black.webp
    - assets/images/search_white.png
    - assets/images/Contact_Female.webp
    - assets/images/Contact_Male.webp
    - assets/images/right_more.png
    - assets/images/favorite.webp
    - assets/images/contacts_add_newmessage.png
    - assets/images/add_addressicon.png
    - assets/images/ic_delete.webp
    - assets/images/ic_right_arrow_black.webp
    - assets/images/ic_right_arrow_grey.webp
    - assets/images/ic_add_friend.webp
    - assets/images/ic_no_data.webp

    - assets/images/mine/ic_small_code.png
    - assets/images/mine/ic_wallet.webp
    - assets/images/mine/ic_card_package.png
    - assets/images/mine/ic_emoji.png
    - assets/images/mine/ic_pay.png
    - assets/images/mine/ic_setting.png
    - assets/images/mine/ic_collections.png
    - assets/images/mine/ic_album.png
    - assets/images/mine/ic_social_circle.png

    - assets/images/contact/ic_contacts_details.png
    - assets/images/contact/ic_no_public.webp
    - assets/images/contact/ic_tag.webp
    - assets/images/contact/ic_group.webp
    - assets/images/contact/ic_new_friend.webp
    - assets/images/contact/ic_video.png
    - assets/images/contact/ic_voice.png
    - assets/images/contact/ic_offical.webp
    - assets/images/contact/ic_reda.webp
    - assets/images/contact/ic_scanqr.webp
    - assets/images/contact/ic_search_wework.webp
    - assets/images/contact/ic_contact_add.webp

    - assets/images/discover/ff_Icon_album.webp
    - assets/images/discover/ff_Icon_shake.webp
    - assets/images/discover/ff_Icon_bottle.webp
    - assets/images/discover/ff_Icon_browse.webp
    - assets/images/discover/ff_Icon_nearby.webp
    - assets/images/discover/ff_Icon_qr_code.webp
    - assets/images/discover/ff_Icon_search.webp
    - assets/images/discover/game_center_h5.webp
    - assets/images/discover/mini_program.webp

    - assets/images/group/
